from django.db import models

# Create your models here.

from django.db import models


class Review(models.Model):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        RUNNING = "running", "Running"
        COMPLETED = "completed", "Completed"
        FAILED = "failed", "Failed"

    repository_url = models.URLField(
        blank=True,
        null=True,
        help_text="Optional GitHub repository URL.",
    )

    code = models.TextField(
        help_text="Source code submitted for review.",
    )

    requirements = models.TextField(
        help_text="What the code is expected to accomplish.",
    )

    language = models.CharField(
        max_length=50,
        help_text="Programming language of the submitted code.",
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )

    final_report = models.JSONField(
        blank=True,
        null=True,
        help_text="Final structured report generated by the agents.",
    )

    error_message = models.TextField(
        blank=True,
        null=True,
        help_text="Error message if the review fails.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    started_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    completed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"Review #{self.id}"



class Finding(models.Model):
    class Severity(models.TextChoices):
        CRITICAL = "critical", "Critical"
        HIGH = "high", "High"
        MEDIUM = "medium", "Medium"
        LOW = "low", "Low"
        INFO = "info", "Info"

    class VerificationStatus(models.TextChoices):
        PENDING = "pending", "Pending"
        VERIFIED = "verified", "Verified"
        REJECTED = "rejected", "Rejected"

    review = models.ForeignKey(
        Review,
        on_delete=models.CASCADE,
        related_name="findings",
    )

    title = models.CharField(
        max_length=255,
    )

    severity = models.CharField(
        max_length=20,
        choices=Severity.choices,
    )

    file_path = models.CharField(
        max_length=500,
        blank=True,
    )

    line_number = models.PositiveIntegerField(
        blank=True,
        null=True,
    )

    evidence = models.TextField(
        help_text="Relevant code or evidence supporting the finding.",
    )

    explanation = models.TextField()

    suggested_fix = models.TextField()

    confidence = models.FloatField(
        blank=True,
        null=True,
        help_text="Confidence score between 0 and 1.",
    )

    verification_status = models.CharField(
        max_length=20,
        choices=VerificationStatus.choices,
        default=VerificationStatus.PENDING,
    )

    verification_reason = models.TextField(
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return f"{self.title} - Review #{self.review_id}"


class AgentTrajectory(models.Model):
    review = models.ForeignKey(
        Review,
        on_delete=models.CASCADE,
        related_name="trajectories",
    )

    agent_name = models.CharField(
        max_length=100,
    )

    step = models.PositiveIntegerField(
        default=1,
        help_text="Order in which this agent executed.",
    )

    input_data = models.JSONField()

    output_data = models.JSONField()

    status = models.CharField(
        max_length=20,
        choices=[
            ("started", "Started"),
            ("completed", "Completed"),
            ("failed", "Failed"),
        ],
        default="started",
    )

    started_at = models.DateTimeField(
        auto_now_add=True,
    )

    completed_at = models.DateTimeField(
        blank=True,
        null=True,
    )

    error_message = models.TextField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return (
            f"{self.review} - "
            f"{self.agent_name} - "
            f"Step {self.step}"
        )