# Generated by Django 6.1 on 2026-08-31 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField(blank=True, help_text='Optional GitHub repository URL.', null=True)),
                ('code', models.TextField(help_text='Source code submitted for review.')),
                ('requirements', models.TextField(help_text='What the code is expected to accomplish.')),
                ('language', models.CharField(help_text='Programming language of the submitted code.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('final_report', models.JSONField(blank=True, help_text='Final structured report generated by the agents.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the review fails.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence', models.TextField(help_text='Relevant code or evidence supporting the finding.')),
                ('explanation', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score between 0 and 1.', null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('step', models.PositiveIntegerField(default=1, help_text='Order in which this agent executed.')),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='reviews.review')),
            ],
        ),
    ]
