# Generated by Django 6.1 on 2026-08-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_agenttrajectory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenttrajectory',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='respositry_url',
        ),
        migrations.AddField(
            model_name='agenttrajectory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenttrajectory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenttrajectory',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20),
        ),
        migrations.AddField(
            model_name='agenttrajectory',
            name='step',
            field=models.PositiveIntegerField(default=1, help_text='Order in which this agent executed.'),
        ),
        migrations.AddField(
            model_name='review',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the review fails.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='final_report',
            field=models.JSONField(blank=True, help_text='Final structured report generated by the agents.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='repository_url',
            field=models.URLField(blank=True, help_text='Optional GitHub repository URL.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='code',
            field=models.TextField(help_text='Source code submitted for review.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='language',
            field=models.CharField(help_text='Programming language of the submitted code.', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='requirements',
            field=models.TextField(help_text='What the code is expected to accomplish.'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence', models.TextField(help_text='Relevant code or evidence supporting the finding.')),
                ('explanation', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score between 0 and 1.', null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.review')),
            ],
        ),
    ]
