import re
from dataclasses import dataclass


@dataclass
class CodeChunk:
    """
    Represents one independently reviewable piece of code.
    """

    index: int
    content: str
    file_path: str = ""

    @property
    def label(self):
        if self.file_path:
            return self.file_path

        return f"Code Chunk {self.index}"


class CodeChunker:
    """
    Splits submitted source code into AI-friendly chunks.

    The chunker understands the file markers generated by
    GitHubService / ReviewViewSet and can also handle pasted
    source code that doesn't have file markers.
    """

    # Approximate characters per token.
    #
    # This is intentionally conservative. We don't want to
    # approach Groq's 8,000 TPM limit too closely.
    CHARS_PER_TOKEN = 4

    # Keep the actual code portion below this.
    #
    # Prompts + system instructions + AI output consume tokens too.
    TARGET_CODE_TOKENS = 2_500

    TARGET_CHARS = (
        TARGET_CODE_TOKENS * CHARS_PER_TOKEN
    )

    # Avoid producing extremely tiny chunks.
    MIN_CHUNK_CHARS = 1_000

    FILE_SEPARATOR_PATTERN = re.compile(
        r"={40,}\s*"
        r"FILE:\s*(.*?)\s*"
        r"={40,}",
        re.MULTILINE,
    )

    def chunk(self, code: str):
        if not code or not code.strip():
            return []

        files = self._extract_files(code)

        if files:
            return self._chunk_files(files)

        return self._chunk_plain_code(
            code=code,
            file_path="",
        )

    # ---------------------------------------------------------
    # FILE EXTRACTION
    # ---------------------------------------------------------

    def _extract_files(self, code):
        matches = list(
            self.FILE_SEPARATOR_PATTERN.finditer(code)
        )

        if not matches:
            return []

        files = []

        for index, match in enumerate(matches):

            file_path = match.group(1).strip()

            content_start = match.end()

            if index + 1 < len(matches):
                content_end = matches[index + 1].start()
            else:
                content_end = len(code)

            content = code[
                content_start:content_end
            ].strip()

            if not content:
                continue

            files.append(
                {
                    "file_path": file_path,
                    "content": content,
                }
            )

        return files

    # ---------------------------------------------------------
    # FILE-BASED CHUNKING
    # ---------------------------------------------------------

    def _chunk_files(self, files):
        chunks = []

        current_content = []
        current_size = 0

        for file_data in files:

            file_path = file_data["file_path"]
            content = file_data["content"]

            formatted_file = (
                f"FILE: {file_path}\n"
                f"{'-' * 60}\n"
                f"{content}\n"
            )

            file_size = len(formatted_file)

            # If the file itself fits into the current chunk,
            # add it.
            if (
                current_content
                and
                current_size + file_size
                > self.TARGET_CHARS
            ):
                chunks.append(
                    self._create_chunk(
                        chunks,
                        current_content,
                    )
                )

                current_content = []
                current_size = 0

            # If a single file is larger than the target,
            # split the file itself.
            if file_size > self.TARGET_CHARS:

                if current_content:
                    chunks.append(
                        self._create_chunk(
                            chunks,
                            current_content,
                        )
                    )

                    current_content = []
                    current_size = 0

                file_chunks = (
                    self._chunk_plain_code(
                        code=content,
                        file_path=file_path,
                        existing_count=len(chunks),
                    )
                )

                chunks.extend(file_chunks)

                continue

            current_content.append(
                formatted_file
            )

            current_size += file_size

        if current_content:
            chunks.append(
                self._create_chunk(
                    chunks,
                    current_content,
                )
            )

        return chunks

    # ---------------------------------------------------------
    # PLAIN CODE / LARGE FILE CHUNKING
    # ---------------------------------------------------------

    def _chunk_plain_code(
        self,
        code,
        file_path="",
        existing_count=0,
    ):
        lines = code.splitlines(
            keepends=True
        )

        chunks = []

        current_lines = []
        current_size = 0

        for line in lines:

            line_size = len(line)

            if (
                current_lines
                and
                current_size + line_size
                > self.TARGET_CHARS
            ):
                chunks.append(
                    CodeChunk(
                        index=(
                            existing_count
                            + len(chunks)
                            + 1
                        ),
                        content=self._format_chunk(
                            current_lines,
                            file_path,
                        ),
                        file_path=file_path,
                    )
                )

                current_lines = []
                current_size = 0

            current_lines.append(line)
            current_size += line_size

        if current_lines:
            chunks.append(
                CodeChunk(
                    index=(
                        existing_count
                        + len(chunks)
                        + 1
                    ),
                    content=self._format_chunk(
                        current_lines,
                        file_path,
                    ),
                    file_path=file_path,
                )
            )

        return chunks

    # ---------------------------------------------------------
    # HELPERS
    # ---------------------------------------------------------

    def _format_chunk(
        self,
        lines,
        file_path,
    ):
        content = "".join(lines).strip()

        if file_path:
            return (
                f"FILE: {file_path}\n"
                f"{'-' * 60}\n"
                f"{content}"
            )

        return content

    def _create_chunk(
        self,
        chunks,
        content_parts,
    ):
        content = "\n".join(
            content_parts
        ).strip()

        return CodeChunk(
            index=len(chunks) + 1,
            content=content,
        )